import { useState, useEffect } from "react";
import { Repository, RoadmapStep } from "../../types";
import { backendService } from "../../services/backend";
import { CheckCircle2, Circle, Play, FileText, ArrowRight } from "lucide-react";

interface RoadmapViewProps {
  repo: Repository;
}

export function RoadmapView({ repo }: RoadmapViewProps) {
  const [steps, setSteps] = useState<RoadmapStep[]>([]);
  const [activeStepIdx, setActiveStepIdx] = useState(0);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let active = true;
    const fetchRoadmap = async () => {
      setLoading(true);
      try {
        const data = await backendService.getLearningRoadmap(repo.path);
        if (active) {
          setSteps(data);
          // Set active step to first 'current' step or 0
          const currentIdx = data.findIndex(s => s.status === "current");
          setActiveStepIdx(currentIdx !== -1 ? currentIdx : 0);
        }
      } catch (err) {
        console.error(err);
      } finally {
        if (active) setLoading(false);
      }
    };
    fetchRoadmap();
    return () => {
      active = false;
    };
  }, [repo]);

  return (
    <div className="h-full flex flex-col animate-fade-in space-y-4">
      {/* Page Header */}
      <div>
        <h2 className="text-xl font-bold text-white tracking-tight">Codebase Learning Roadmap</h2>
        <p className="text-xs text-gray-400 mt-1">
          A personalized onboarding sequence generated by local AI. Read files in this order to understand the flow.
        </p>
      </div>

      {loading ? (
        <div className="flex-1 flex items-center justify-center min-h-[300px]">
          <div className="h-6 w-6 rounded-full border-2 border-primary border-t-transparent animate-spin"></div>
        </div>
      ) : (
        <div className="flex-1 grid md:grid-cols-5 gap-6 items-start">
          
          {/* Left: Interactive Vertical Steps Timeline */}
          <div className="md:col-span-2 space-y-3">
            {steps.map((step, idx) => {
              const isActive = activeStepIdx === idx;
              const isDone = step.status === "done";
              const isCurrent = step.status === "current";

              return (
                <button
                  key={step.id}
                  onClick={() => setActiveStepIdx(idx)}
                  className={`w-full text-left p-4 rounded-2xl glass-panel border flex gap-3.5 items-start transition-all relative ${
                    isActive 
                      ? "bg-primary/10 border-primary/20" 
                      : "bg-white/[0.01] hover:bg-white/[0.03] border-white/5 hover:border-white/10"
                  }`}
                >
                  {/* Timeline Indicator Ring */}
                  <div className="mt-0.5 shrink-0">
                    {isDone ? (
                      <CheckCircle2 className="h-5 w-5 text-success fill-success/15" />
                    ) : isCurrent ? (
                      <Play className="h-5 w-5 text-primary fill-primary/15 animate-pulse" />
                    ) : (
                      <Circle className="h-5 w-5 text-gray-600" />
                    )}
                  </div>

                  <div className="min-w-0 text-xs">
                    <span className="text-[9px] text-gray-500 font-semibold uppercase tracking-wider block mb-1">
                      Step {idx + 1}
                    </span>
                    <h4 className={`font-bold truncate ${isActive ? "text-white text-sm" : "text-gray-300"}`}>
                      {step.title}
                    </h4>
                    <p className="text-gray-400 mt-1 line-clamp-2 leading-relaxed">
                      {step.description}
                    </p>
                  </div>
                </button>
              );
            })}
          </div>

          {/* Right: Selected Step Explanations & Files */}
          <div className="md:col-span-3 glass-panel p-5 rounded-2xl border border-white/5 bg-white/[0.01] min-h-[350px] space-y-5 animate-fade-in">
            {steps[activeStepIdx] && (
              <>
                <div>
                  <span className="px-2 py-0.5 rounded bg-accent/10 border border-accent/20 text-[9px] font-bold text-accent uppercase tracking-wider">
                    Step Study Guide
                  </span>
                  <h3 className="text-lg font-bold text-white mt-1.5">{steps[activeStepIdx].title}</h3>
                  <p className="text-xs text-gray-400 mt-1 leading-relaxed">
                    {steps[activeStepIdx].description}
                  </p>
                </div>

                {/* Recommended Reading Files */}
                <div className="space-y-2">
                  <h4 className="text-xs font-bold text-white uppercase tracking-wider flex items-center gap-1.5">
                    <FileText className="h-4 w-4 text-primary" />
                    Files to inspect
                  </h4>
                  <div className="space-y-1.5">
                    {steps[activeStepIdx].files.map((file) => (
                      <a
                        key={file}
                        href={`file:///${repo.path}/${file}`}
                        className="flex items-center justify-between p-2.5 rounded-xl bg-white/[0.02] hover:bg-white/[0.04] border border-white/5 hover:border-white/10 font-mono text-[11px] text-gray-300 transition-colors group"
                      >
                        <span className="truncate group-hover:text-primary transition-colors">{file}</span>
                        <ArrowRight className="h-3 w-3 text-gray-600 group-hover:text-primary transition-colors shrink-0 ml-2" />
                      </a>
                    ))}
                  </div>
                </div>

                {/* AI Explanations */}
                <div className="space-y-2.5 pt-2 border-t border-white/5 text-xs">
                  <h4 className="font-bold text-gray-400">Step Explanations</h4>
                  <div className="space-y-2">
                    {steps[activeStepIdx].explanations.map((exp, i) => (
                      <div key={i} className="flex gap-2.5 items-start text-gray-300 leading-relaxed font-medium">
                        <span className="text-primary/70 shrink-0 font-bold">·</span>
                        <span>{exp}</span>
                      </div>
                    ))}
                  </div>
                </div>
              </>
            )}
          </div>

        </div>
      )}
    </div>
  );
}
